[package]
name = "voxels"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "voxels"
crate-type = ["cdylib"]

[dependencies]
bevy = { version = "0.19.1", default-features = false, features = ["async_executor", "bevy_gltf", "bevy_pbr", "gltf_animation", "pbr_transmission_textures", "png", "reflect_auto_register"] }
either = { version = "1.17.0", default-features = false }
glam = { version = "0.33.3", default-features = false, features = ["f64", "std"] }
png = { version = "0.18.1", default-features = false }
pyo3 = { version = "0.29.1", default-features = false, features = ["either", "experimental-inspect", "macros"] }
serde = { version = "1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
