[package]
name = "voxels"
description = "Create and animate voxel models with support for PBR materials, preview them and export them in glTF scenes."
authors = ["Benjamin Lefebvre"]
version = "0.1.0"
keywords = ["3d", "assets", "gltf", "voxel"]
license = "MIT"
edition = "2024"
publish = false

[lib]
name = "voxels"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "fat"
strip = "debuginfo"

[dependencies]
anyhow = { version = "1.0.104", default-features = false, features = ["std"] }
clap = { version = "4.5", default-features = false, features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage"] }
either = { version = "1.17.0", default-features = false }
glam = { version = "0.33.6", default-features = false, features = ["f64", "std"] }
png = { version = "0.18.1", default-features = false }
pyo3 = { version = "0.29.2", default-features = false, features = ["abi3-py38", "either", "experimental-inspect", "macros"] }
serde = { version = "1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
thiserror = { version = "2.0.20", default-features = false, features = ["std"] }
uuid = { version = "1.26.0", default-features = false, features = ["v4"] }
