[package]
name = "voxels"
description = "Create and animate voxel models with support for PBR materials, preview them and export them in glTF scenes"
authors = ["Benjamin Lefebvre"]
version = "0.1.0"
keywords = ["3d", "assets", "gltf", "voxel"]
license = "MIT"
edition = "2024"
publish = false

[lib]
name = "voxels"
crate-type = ["cdylib"]

[dependencies]
bevy = { version = "0.19.1", default-features = false, features = ["async_executor", "bevy_gltf", "bevy_pbr", "gltf_animation", "pbr_transmission_textures", "png", "reflect_auto_register"] }
either = { version = "1.17.0", default-features = false }
glam = { version = "0.33.5", default-features = false, features = ["f64", "std"] }
png = { version = "0.18.1", default-features = false }
pyo3 = { version = "0.29.2", default-features = false, features = ["abi3-py38", "either", "experimental-inspect", "macros"] }
serde = { version = "1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
