class Color:
    def __init__(self, rgba: tuple[int, int, int], *, roughness: float = 1.0, metallic: float = 0.0, ior: float = 1.5, transmission: float = 0.0, emissive: float = 0.0) -> None: ...

class Scene:
    ...