class Vec3:
    ZERO: Vec3
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def __neg__(self) -> Vec3: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, other: float | Vec3) -> Vec3: ...
    def __div__(self, other: float) -> Vec3: ...

class Quat:
    IDENTITY: Quat
    @staticmethod
    def from_rotation_x(angle: float) -> Quat: ...
    @staticmethod
    def from_rotation_y(angle: float) -> Quat: ...
    @staticmethod
    def from_rotation_z(angle: float) -> Quat: ...
    def conjugate(self) -> Quat: ...
    def __mul__(self, other: Quat) -> Quat: ...

class Palette:
    def __init__(self) -> None: ...
    def add_color(self, rgb: tuple[int, int, int], *, roughness: float = 1.0, metallic: float = 0.0, ior: float = 1.5, transmission: float = 0.0, emissive: float = 0.0) -> Color: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Color: ...

class Color:
    ...

class Scene:
    def __init__(self) -> None: ...
    def create_root_node(self, name: str) -> Node: ...

class Node:
    def create_child_node(self, name: str) -> Node: ...
