from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import Final, final

@final
class Anim:
    def add_rotation(self, /, node: Node, input: Sequence[float], output: Sequence[Quat], *, interpolation: Interpolation |None = None) -> None: ...
    def add_scale(self, /, node: Node, input: Sequence[float], output: Sequence[Vec3], *, interpolation: Interpolation |None = None) -> None: ...
    def add_translation(self, /, node: Node, input: Sequence[float], output: Sequence[Vec3], *, interpolation: Interpolation |None = None) -> None: ...
    @property
    def extras(self, /) -> dict[str, str] |None: ...
    @property
    def name(self, /) -> str: ...
    @property
    def scene(self, /) -> Scene: ...

@final
class CameraAngle:
    def __new__(cls, /, yaw: float, pitch: float, *, zoom: float |None = None) -> CameraAngle: ...
    @property
    def pitch(self, /) -> float: ...
    @property
    def yaw(self, /) -> float: ...
    @property
    def zoom(self, /) -> float |None: ...

@final
class Color:
    def __new__(cls, /, r: int, g: int, b: int) -> Color: ...
    @property
    def b(self, /) -> int: ...
    @property
    def g(self, /) -> int: ...
    @property
    def r(self, /) -> int: ...

@final
class Dimensions:
    def __new__(cls, /, x: int, y: int, z: int) -> Dimensions: ...
    def contains(self, /, a: tuple[int, int, int]) -> bool: ...
    @property
    def x(self, /) -> int: ...
    @property
    def y(self, /) -> int: ...
    @property
    def z(self, /) -> int: ...

@final
class Interpolation:
    CubicSpline: Final[Interpolation]
    Linear: Final[Interpolation]
    Step: Final[Interpolation]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class Material:
    @property
    def color(self, /) -> Color: ...
    @property
    def emissive(self, /) -> float: ...
    @property
    def ior(self, /) -> float: ...
    @property
    def metallic(self, /) -> float: ...
    @property
    def palette(self, /) -> Palette: ...
    @property
    def roughness(self, /) -> float: ...
    @property
    def transmission(self, /) -> float: ...
    @property
    def volume(self, /) -> Volume |None: ...

@final
class Mesh:
    @property
    def extras(self, /) -> dict[str, str] |None: ...
    @property
    def model(self, /) -> Model: ...
    @property
    def name(self, /) -> str: ...
    @property
    def parent(self, /) -> Node: ...

@final
class Model:
    def __new__(cls, /, dims: Dimensions, palette: Palette, pivot: Pivot |Vec3) -> Model: ...
    def aabb(self, /, material: Material |None, a: tuple[int, int, int], b: tuple[int, int, int]) -> None: ...
    def copy(self, /) -> Model: ...
    @property
    def dims(self, /) -> Dimensions: ...
    def flip_x(self, /) -> Model: ...
    def flip_y(self, /) -> Model: ...
    def flip_z(self, /) -> Model: ...
    def include(self, /, other: Model, offset: tuple[int, int, int]) -> None: ...
    @property
    def palette(self, /) -> Palette: ...
    @property
    def pivot(self, /) -> Pivot |Vec3: ...
    def put(self, /, material: Material |None, pos: tuple[int, int, int]) -> None: ...
    def render(self, /, angles: Sequence[CameraAngle]) -> RenderOutput: ...
    def spheroid(self, /, material: Material |None, c: tuple[int, int, int], r1: int, r2: int |None = None, r3: int |None = None) -> None: ...

@final
class Node:
    def add_model(self, /, name: str, model: Model, *, extras: dict[str, str] |None = None) -> Mesh: ...
    def create_child_node(self, /, name: str, *, translation: Vec3 |None = None, rotation: Quat |None = None, scale: Vec3 |None = None, extras: dict[str, str] |None = None) -> Node: ...
    @property
    def extras(self, /) -> dict[str, str] |None: ...
    @property
    def name(self, /) -> str: ...
    @property
    def parent(self, /) -> Node |None: ...
    @property
    def rotation(self, /) -> Quat |None: ...
    @property
    def scale(self, /) -> Vec3 |None: ...
    @property
    def scene(self, /) -> Scene: ...
    @property
    def translation(self, /) -> Vec3 |None: ...

@final
class Palette:
    def __len__(self, /) -> int: ...
    def __new__(cls, /) -> Palette: ...
    def add_material(self, /, color: Color, *, roughness: float = 1.0, metallic: float = 0.0, ior: float = 1.5, transmission: float = 0.0, emissive: float = 0.0, volume: Volume |None = None) -> Material: ...

@final
class Pivot:
    BottomCenter: Final[Pivot]
    Center: Final[Pivot]
    Corner: Final[Pivot]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class Quat:
    """
    A quaternion, with double precisions components.
    """
    IDENTITY: Final[Quat]
    """
    The identity quaternion, equivalent to no rotation.
    """
    def __mul__(self, other: object, /) -> Quat:
        """
        Quaternion product, `other` must be a `Quat`.
        """
    def conjugate(self, /) -> Quat: ...
    @staticmethod
    def from_axis_angle(axis: Vec3, angle: float) -> Quat:
        """
        Creates a quaternion that rotates `angle` degrees around `axis`.
        `axis` does not need to be normalized.
        """
    @staticmethod
    def from_rotation_x(angle: float) -> Quat:
        """
        Creates a quaternion that rotates `angle` degrees around the x axis.
        """
    @staticmethod
    def from_rotation_y(angle: float) -> Quat:
        """
        Creates a quaternion that rotates `angle` degrees around the y axis.
        """
    @staticmethod
    def from_rotation_z(angle: float) -> Quat:
        """
        Creates a quaternion that rotates `angle` degrees around the z axis.
        """

@final
class RenderOutput:
    @property
    def files(self, /) -> list[Path]: ...

@final
class Scene:
    def __new__(cls, /) -> Scene: ...
    def create_anim(self, /, name: str, *, extras: dict[str, str] |None = None) -> Anim: ...
    def create_root_node(self, /, name: str, *, extras: dict[str, str] |None = None) -> Node: ...
    def export_glb(self, /, path: str |PathLike[str]) -> None: ...
    def render(self, /, angles: Sequence[CameraAngle], *, times: Sequence[float] = ..., animation: str |None = None, include: Sequence[str] |None = None, exclude: Sequence[str] |None = None) -> RenderOutput: ...

@final
class Vec3:
    """
    A 3-dimensional real column vector, with double precision components.
    """
    ONES: Final[Vec3]
    """
    A vector that only contains ones.
    """
    ZERO: Final[Vec3]
    """
    A vector that only contains zeros.
    """
    def __add__(self, other: object, /) -> Vec3:
        """
        Component-wise addition of `self` and `other`.
        
        `other` must be a `Vec3`.
        """
    def __mul__(self, other: object, /) -> Vec3:
        """
        Scaling of `self` by the scalar factor `other`.
        
        `other` must be a `float`.
        """
    def __neg__(self, /) -> Vec3: ...
    def __new__(cls, /, x: float, y: float, z: float) -> Vec3: ...
    def __sub__(self, other: object, /) -> Vec3:
        """
        Component-wise subtraction of `self` and `other`.
        
        `other` must be a `Vec3`.
        """
    def __truediv__(self, other: object, /) -> Vec3:
        """
        Scaling of `self` by the scalar factor `other⁻¹`.
        
        `other` must be a `float`.
        """
    @staticmethod
    def splat(t: float) -> Vec3: ...
    @property
    def x(self, /) -> float: ...
    @property
    def y(self, /) -> float: ...
    @property
    def z(self, /) -> float: ...

@final
class Volume:
    def __new__(cls, /, color: Color, distance: float, *, thickness: float = 1.0) -> Volume: ...
    @property
    def color(self, /) -> Color: ...
    @property
    def distance(self, /) -> float: ...
    @property
    def thickness(self, /) -> float: ...
